const express = require('express')
const fs = require("fs");
const bodyParser = require('body-parser')

const server = express();

server.get('/params/:param&:param2&:param3&:param4', (req, res) => {
 res.send({ message: `HOLA tu parametro ${req.params.param}  ${req.params.param2} ${req.params.param3} ${req.params.param4}`}) 
 generarSTL(req.params.width )
})

server.listen(8000, () => {
    console.log('En puerto 8000')
})


function generarSTL() {
    var STLString = " solid STL generated by MeshLab";

    //Generar caras horizontales 

    //Generar caras verticales





    fs.writeFile('./exit.stl', STL(), (err) => {
        if (err) console.log(err)
      })

    STLString += `\n facet normal ${arrayVecN[i].x} ${arrayVecN[i].y} ${arrayVecN[i].z}`
    STLString += `\n  outer loop` 
    STLString += `\n   vertex ${arrayPoints[i].x} ${arrayPoints[i].y} ${arrayPoints[i].z}`
    STLString += `\n   vertex ${arrayPoints[i+1].x} ${arrayPoints[i+1].y} ${arrayPoints[i+1].z}` 
    STLString += `\n   vertex ${vertice.x} ${vertice.y} ${vertice.z}`
    STLString += `\n  endloop`
    STLString += `\n endfacet`
    
}


function multiplicarVectores(v1, v2) {
    let vec = new Object();
    vec.x = (v1.y*v2.z - v1.z*v2.y)
    vec.y = (v1.z*v2.x - v1.x*v2.z)
    vec.z = (v1.x*v2.y - v1.y*v2.x)
    return vec;
  }


